# Generated by Django 5.1.7 on 2025-04-02 19:28
# Generated by Django 4.2.20 on 2025-04-12 13:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='وقت الدخول')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='وقت الخروج')),
                ('status', models.CharField(choices=[('present', 'موجود ✅'), ('absent', 'غير موجود ❌')], default='present', max_length=10, verbose_name='الحالة')),
                ('shift_type', models.CharField(choices=[('morning', 'صباحي 🌞'), ('night', 'ليلي 🌙')], default='morning', max_length=10, verbose_name='نوع الدوام')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'سجل الدوام',
                'verbose_name_plural': 'سجلات الدوام',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_devices', models.CharField(choices=[('camera_1', 'كاميرا دخول'), ('camera_2', 'كاميرا ميزان 1 '), ('camera_3', 'كاميرا ميزان 2'), ('camera_4', 'كاميرا خروج '), ('denice_weight_1', 'جهاز وزن 1'), ('denice_weight_2', 'جهاز وزن 2')], max_length=20, verbose_name='اسم الجهاز')),
                ('address_ip', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('connection_type', models.CharField(choices=[('wifi', 'WiFi'), ('serial', 'Serial')], max_length=10, verbose_name='نوع الاتصال')),
                ('device_status', models.BooleanField(default=True, verbose_name='حالة الجهاز')),
                ('location', models.CharField(choices=[('entry', 'دخول'), ('exit', 'خروج'), ('امام الميزان 1', 'امام الميزان 1'), ('امام الميزان 2', 'امام الميزان 2')], max_length=20, verbose_name='موقع الجهاز')),
                ('port_number', models.CharField(default='COM1', max_length=50, verbose_name='رقم المنفذ')),
                ('baud_rate', models.CharField(choices=[('9600', '9600'), ('19200', '19200'), ('38400', '38400'), ('57600', '57600'), ('115200', '115200')], default='9600', max_length=50, verbose_name='معدل الباود')),
                ('initialization_data_size', models.PositiveIntegerField(choices=[(5, '5'), (6, '6'), (7, '7'), (8, '8')], default=8, verbose_name='حجم بيانات التهيئة')),
                ('number_of_initialization_bits', models.PositiveIntegerField(choices=[(1, '1'), (2, '2')], default=1, verbose_name='عدد بتات التهيئة')),
                ('parity_type', models.CharField(choices=[('None', 'None'), ('Even', 'Even'), ('Odd', 'Odd')], default='None', max_length=10, verbose_name='نوع التماثل')),
                ('flow_control', models.CharField(choices=[('None', 'None'), ('XON/XOFF', 'XON/XOFF'), ('RTS/CTS', 'RTS/CTS')], default='None', max_length=20, verbose_name='التحكم بالتدفق')),
                ('number_of_digits_after_decimal_point', models.PositiveSmallIntegerField(default=2, verbose_name='عدد الأرقام بعد العلامة العشرية')),
                ('last_date_settings_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تاريخ لتحديث الإعدادات')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المستخدم')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='كلمة المرور')),
            ],
            options={
                'verbose_name': ' الجهاز',
                'verbose_name_plural': ' الأجهزة',
            },
        ),
        migrations.CreateModel(
            name='DriverNeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='يجب أن يحتوي اسم السائق على أحرف فقط ولا يُسمح بالأرقام.', regex='^[a-zA-Z\\u0600-\\u06FF\\s]+$')], verbose_name='اسم السائق')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="رقم الهاتف يجب أن يكون بين 9 و 15 رقمًا ويمكن أن يبدأ بعلامة '+'", regex='^\\+?\\d{9,15}$')], verbose_name='رقم الهاتف')),
                ('address', models.CharField(max_length=15, verbose_name='العنوان')),
                ('card_number', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message=' يجب ان يكون رقم البطاقة بين 9 و 25 رقما ولا يحتوي على رموز.', regex='^\\d{9,25}$')], verbose_name='رقم البطاقة')),
                ('date_of_registration', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('number_of_trucks', models.PositiveIntegerField(verbose_name='عدد الشاحنات')),
            ],
            options={
                'verbose_name': 'السائق',
                'verbose_name_plural': 'السائقيين',
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Entry_and_exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('process_entry', 'عملية دخول'), ('process_exit', 'عملية خروج')], max_length=50, verbose_name='العمليه')),
                ('image_path_entry', models.ImageField(upload_to='entry_images/%y/%m/%d', verbose_name='صور الدخول')),
                ('image_path_exit', models.ImageField(blank=True, null=True, upload_to='exit_images/%y/%m/%d', verbose_name='صور الخروج')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('exit_date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_companies.devices', verbose_name='الكاميرا')),
            ],
            options={
                'verbose_name': 'عمليات الدخول الخروج',
                'verbose_name_plural': '  عمليات الدخول الخروج',
            },
        ),
        migrations.CreateModel(
>>>>>>> e7530f7db55fa32fe665305653f5768606311b06
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('dry', 'المواد الجافة'), ('liquid', 'المواد السائلة'), ('heavy_machinery', 'الآلات الثقيلة والمركبات'), ('containers', 'الحاويات')], max_length=50, verbose_name='فئة المادة')),
                ('name_material', models.CharField(max_length=20, verbose_name='الماده')),
                ('description', models.TextField()),
                ('unit', models.CharField(choices=[('ton', 'طن'), ('cubic_meter', 'متر مكعب'), ('kg', 'كجم'), ('piece', 'بالحبة')], max_length=20, verbose_name='وحدة القياس')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='إذا كانت الوحدة (طن، متر مكعب، كجم) أدخل قيمة عشرية، وإذا كانت (بالحبة) أدخل رقماً صحيحاً فقط.', max_digits=10, null=True, verbose_name='الوزن')),
                ('density', models.DecimalField(blank=True, decimal_places=3, help_text='يظهر فقط للمواد السائلة', max_digits=10, null=True, verbose_name='الكثافة')),
                ('hazard_level', models.CharField(blank=True, choices=[('flammable', 'قابلة للاشتعال'), ('toxic', 'سام'), ('non_hazardous', 'غير خطرة')], max_length=20, null=True, verbose_name='مستوى الخطورة')),
                ('date_and_time', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت الاضافة')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر لكل وحدة')),
            ],
            options={
                'verbose_name': 'الماده',
                'verbose_name_plural': ' المواد ',
            },
        ),
        migrations.CreateModel(
            name='TrucksTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='الشركه المصنعه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الطول (متر)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='العرض (متر)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الارتفاع (متر)')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
                ('date_of_registration', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'نوع الشاحنة',
                'verbose_name_plural': 'أنواع الشاحنات',
            },
        ),
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='رقم اللوحه')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('condition', models.BooleanField(default=True, verbose_name='الحالة')),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_companies.driverneme', verbose_name='اسم السائق')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_companies.truckstypes', verbose_name='نوع الشاحنه')),
            ],
            options={
                'verbose_name': 'الشاحنه',
                'verbose_name_plural': 'الشاحنات',
            },
        ),
        migrations.CreateModel(
            name='Entry_and_exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path_entry', models.ImageField(upload_to='entry_images/%y/%m/%d', verbose_name='صور الدخول')),
                ('image_path_exit', models.ImageField(upload_to='exit_images/%y/%m/%d', verbose_name='صور الخروج')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('exit_date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_companies.devices', verbose_name='الكاميرا')),
                ('plate_number_E_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_companies.trucks', verbose_name='رقم اللوحه')),
            ],
            options={
                'verbose_name': 'عمليات الدخول الخروج',
                'verbose_name_plural': '  عمليات الدخول الخروج',
            },
        ),
        migrations.CreateModel(
            name='Legal_weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_weight_L_W', models.DecimalField(decimal_places=5, default=0.0, max_digits=10, verbose_name=' الوزن القانوني')),
                ('number_of_axes', models.PositiveIntegerField(verbose_name='عدد المحاور')),
                ('note', models.TextField(default='لا توجد بيانات', help_text='يرجى إدخال وصف المنتج بالتفصيل.', verbose_name='ملاحظه')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('the_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_companies.material', verbose_name='الماده')),
                ('manufacturer_L_W', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_companies.truckstypes', verbose_name='نوع الشاحنه')),
            ],
            options={
                'verbose_name': 'الوزن القانوني',
                'verbose_name_plural': ' الوزن القانوني',
            },
        ),
        migrations.CreateModel(
            name='WeightCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty_weight', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='الوزن الفارغ')),
                ('loaded_weight', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='الوزن المحمل')),
                ('net_weight', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='الوزن الصافي')),
                ('entry_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدخول')),
                ('exit_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الخروج')),
                ('quantity', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='الكمية')),
                ('status', models.CharField(choices=[('incomplete', 'بطاقة غير مكتملة ❌'), ('complete', 'بطاقة مكتملة ✅')], default='incomplete', max_length=10, verbose_name='حالة البطاقة')),
                ('driver_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_companies.driverneme', verbose_name='اسم السائق')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_companies.material', verbose_name='المادة')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_companies.trucks', verbose_name='رقم اللوحة')),
            ],
            options={
                'verbose_name': ' بطاقة الوزن',
                'verbose_name_plural': ' بطاقات الوزن',
            },
        ),
        migrations.CreateModel(
            name='ViolationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت المخالفة')),
                ('image_violation', models.ImageField(upload_to='images_violation/%y/%m/%d', verbose_name='صور المخالفة')),
                ('device_vio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_companies.devices', verbose_name='الكاميرا')),
                ('entry_exit_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_companies.entry_and_exit', verbose_name='العمليه')),
                ('plate_number_vio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_companies.trucks', verbose_name='رقم اللوحه')),
                ('violation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies_manager.violationstype', verbose_name=' نوع المخالفة')),
                ('weight_card_vio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_companies.weightcard', verbose_name='بطاقة الوزن')),
            ],
            options={
                'verbose_name': ' المخالفه',
                'verbose_name_plural': 'المخالفات',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='الكمية')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('net_weight', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='الوزن الصافي')),
<<<<<<< HEAD
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
=======
>>>>>>> e7530f7db55fa32fe665305653f5768606311b06
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_companies.material', verbose_name='الماده')),
                ('weight_card', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system_companies.weightcard', verbose_name='رقم بطاقة الوزن')),
            ],
            options={
                'verbose_name': 'الفاتوره',
                'verbose_name_plural': 'الفواتير',
            },
        ),
    ]
