# Generated by Django 5.1.7 on 2025-04-28 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoice',
            table='system_companies_invoice',
        ),
    ]
