"""
Django settings for a_core project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rj#-z^kx3j+1ay397otg6j8m_8#v^$^$jys6&41vy^&6le)ezc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']

CSRF_TRUSTED_ORIGINS = [ 'https://*' ]

# settings.py
# AUTH_USER_MODEL = 'companies_manager.CustomUser'

SHARED_APPS = [
    'django_tenants',
    # 'admin_adminlte.apps.AdminAdminlteConfig',
    'jazzmin',
    # 'user_management',
    'django.contrib.admin',
    'django.contrib.auth',
    # --------------api------------
    # 'rest_framework',
    'companies_manager.apps.CompaniesManagerConfig',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_htmx',
    'rangefilter',
    'allauth',
    'allauth.account',
]

TENANT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'user_management',
    
    'system_companies',
    # 'companies_manager',
]

INSTALLED_APPS = SHARED_APPS + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

SITE_ID = 1

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'Mutazan_weight.urls'
PUBLIC_SCHEMA_URLCONF = 'Mutazan_weight.urls_public'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Mutazan_weight.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': 'Ali',  # اسم قاعدة البيانات
        'HOST': 'localhost',
        'PORT': '5432',
        'USER': 'AdminMU',
        'PASSWORD':'raed@1234',
    }
}

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

TENANT_MODEL = "companies_manager.Company"
TENANT_DOMAIN_MODEL = "companies_manager.Domain"
SHOW_PUBLIC_IF_NO_TENANT_FOUND = True


# ==================================================================
# ==================================================================

JAZZMIN_SETTINGS = {
    "site_title": "لوحة الإدارة",
    "site_header": "إدارة الشركات",
    "order_with_respect_to": ["companies_manager", "system_companies"],


        # تخصيص الأيقونات في الشريط الجانبي لكل جدول من الجداول في التطبيق


    "custom_links": {
        "companies_manager": [
            {
                "name": "سجل الشركات",
                "url": "/companies/",
                "icon": "fas fa-building",
                # "permissions": ["mutazan_companies.view_company"],
            }
        ],
        "system_companies": [
            {
                "name": "صفحة التقارير",
                "url": "/admin/reports/",
                "icon": "fas fa-chart-line",
            },
        ],
    },

    "custom_sidebar_links": [
        {
            "name": "إدارة الشركات",
            "icon": "fas fa-briefcase",
            "models": [
                "companies_manager.company",
                "system_companies.systemcompany",
            ],
        },
        {
            "name": "التقارير",
            "icon": "fas fa-chart-line",
            "url": "/admin/reports/",
        },
    ],

    "icons": {
        "companies_manager.Company": "fas fa-building",
        "companies_manager.Domain": "fas fa-building",
        "system_companies.Entry_and_exit":"fas fa-sign-in-alt",
        "system_companies.Devices":"fas fa-cogs",
        "system_companies.Invoice":"fas fa-file-invoice",
        "system_companies.WeightCard":"fas fa-weight-hanging",
        "system_companies.Legal_weight":"fas fa-balance-scale",
        "system_companies.Material":"fas fa-box",
        "system_companies.Trucks":"fas fa-truck-moving",
        "system_companies.TrucksTypes":"fas fa-truck",
        "system_companies.DriverNeme":"fas fa-user-tie",
        "system_companies.SystemCompany": "fas fa-cogs",
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "mutazan.YourModel": "fas fa-box",
    },

    # "hide_apps": ["companies_manager"],
    # "hide_models": ["auth.Group", "auth.User"],
    # "site_logo": "images/mutazan.svg",
    # "login_logo": "images/mutazan.svg",

    # "custom_css": "common/css/companies_manager/custom_admin.css",
    # "custom_css": "common/css/custom.css",
    "custom_js": "common/js/system_companies/custom.js",

    "welcome_sign": "مرحبًا بك في لوحة التحكم",

    # "search_model": ["auth.User", "mutazan.YourModel"],

    "topmenu_links": [
        # {"name": "الرئيسية", "url": "admin:index", "permissions": ["auth.view_user"]},
        # {"name": "الدعم الفني", "url": "https://support.example.com", "new_window": True},
        # {"model": "auth.User"},
        # {"app": "mutazan"},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,

    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible"},
    "use_google_fonts_cdn": True,
    "user_avatar": "profile_picture",
    "show_ui_builder": False,
    "language_chooser": True,

    "custom_app_labels": {
        "companies_manager": "إدارة الشركات",
        "system_companies": "نظام الشركة",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "footer_fixed": True,
    "theme": "default",  # يمكنك اختيار سمات مختلفة مثل "default", "darkly", "cosmo", "flatly", إلخ
    "actions_sticky_top": True,
    "right_sidebar": True,
    "usermenu_links": [
        {"model": "auth.user"},
        {"name": "الإشعارات", "url": "/notifications/", "icon": "fas fa-bell"},
        {"name": "الرسائل", "url": "/messages/", "icon": "fas fa-envelope"},
        {"name": "ملء الشاشة", "url": "#", "icon": "fas fa-expand-arrows-alt"},
    ],
    "extrahead": [
        '<link rel="stylesheet" href="{% static "css/custom_admin.css" %}">',
    ],
}



# ==================================================================
# ==================================================================


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
ASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / 'static' ]
STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATICFILES_DIRS = [
#     BASE_DIR / "static",  # مجلد static الرئيسي
#     # BASE_DIR.parent / "books/static",  # مجلد ثانوي للصور إن كان بجانب المشروع
# ]


MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media' 

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
