# Generated by Django 5.1.9 on 2025-05-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_condition',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='الحالة'),
        ),
    ]
