# Generated by Django 4.2.20 on 2025-04-01 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='admin_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies_manager.userprofile', verbose_name='المسؤول الإداري'),
        ),
    ]
